// Regenerates api/src/data.js from the app dataset so the worker can compute
// the daily answer itself. Run after changing characters.json or books.json.
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const src = resolve(here, '../../src/data')

const characters = JSON.parse(readFileSync(resolve(src, 'characters.json'), 'utf8'))
const books = JSON.parse(readFileSync(resolve(src, 'books.json'), 'utf8'))

// Order must match the array the client indexes into, exactly.
const names = characters.map(c => c.name)
const debut = characters.map(c => c.firstEpisode)

const out = `// GENERATED by api/tools/gen_data.mjs — do not edit.
export const NAMES = ${JSON.stringify(names)}
export const DEBUT = ${JSON.stringify(debut)}
export const ARCS = ${JSON.stringify(books.map(b => [b.name, b.endEpisode]))}
`
writeFileSync(resolve(here, '../src/data.js'), out)
console.log(`wrote ${names.length} characters, ${books.length} books`)
